services:
  db:
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_DB: '${POSTGRES_DB}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  rocket:
    restart: on-failure
    depends_on:
      - db
    build: .
    environment:
      ROCKET_ENV: development
      DATABASE_URL: 'postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}'
    ports:
      - '8000:8000'
    volumes:
      - ./src:/app/src
      - ./static:/app/static
      - ./target:/app/target

volumes:
  pgdata: {}
